version: '3.3'

services:
  ldb-timer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
#    volumes:
#      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 96:96
    restart: unless-stopped
